sudo: false
language: python
install:
  - pip install coveralls
script:
  - python3 -m unittest test_linprog_curvefit
  - coverage run --source=requests_oauthlib -m unittest discover
after_success:
  - coveralls